apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  destination:
    namespace: devops-infra
    server: https://kubernetes.default.svc
  project: devops-infra
  source:
    path: devops-infra/harbor/harbor-helm
    helm:
      version: v3
      valueFiles:
      - values.yaml
      - ../values-override.yaml
    repoURL: https://github.com/codeboz/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true