apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kovan-app
  namespace: argocd
spec:
  destination:
    namespace: kovan
    server: https://kubernetes.default.svc
  project: kovan
  source:
    path: kovan/
    repoURL: https://github.com/codeboz/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
