harborAdminPassword: 123qwe123qwe123qwe123qwe
logLevel: error
expose:
  type: ingress
  tls:
    auto:
      commonName: harbor-portal.harbor.cbz.k8s
  ingress:
    className: nginx
    hosts:
      core: harbor-portal.harbor.cbz.k8s
      notary: harbor-notary.harbor.cbz.k8s
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/server-snippet: |
          location / {
            proxy_hide_header 'X-Forwarded-Proto'
          }

          location /v2/ {
            proxy_hide_header 'X-Forwarded-Proto'
          }

          location /service/ {
            proxy_hide_header 'X-Forwarded-Proto'
          }
internalTLS:
  enabled: false
ipFamily:
  ipv6:
    enabled: false
externalURL: http://harbor-portal.harbor.cbz.k8s
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 5Gi
    jobservice:
      size: 2Gi
    chartmuseum:
      size: 2Gi
    trivy:
      size: 5Gi	

